# This file is not in the default docker-compose path, so will be ignored
# unless passed explicitly to docker-compose as we do in our CI configuration.
version: '3'

services:
  test:
    depends_on:
    - pubsub
    - web
    env_file:
    - circleci.env
    environment:
    - PYTEST_ADDOPTS=. tests/integration --ignore tests/load --server=http://web:8000
    - &emulator_host PUBSUB_EMULATOR_HOST=pubsub:8085
  web:
    environment:
    - *emulator_host
