# This file is not in the default docker-compose path, so will be ignored
# unless passed explicitly to docker-compose as we do in our CI configuration.
version: '3'

services:
  test:
    command:
    - --lint
    - .
    - tests/integration
    - --server=http://web:8000
    depends_on:
    - pubsub
    - web
    env_file:
    - circleci.env
    environment:
    - &emulator_host PUBSUB_EMULATOR_HOST=pubsub:8085
  web:
    environment:
    - *emulator_host
