#!/bin/bash

set -exo pipefail

source $(dirname $0)/env

source $(dirname $(dirname $0))/bin/activate

time $(dirname $0)/py-copydedupe --date "$DT" --except 'telemetry_live.main_v*' 'telemetry_live.error_v*' --project_id "$PROJECT"
time $(dirname $0)/py-copydedupe --date "$DT" --slices=100 --only 'telemetry_live.main_v*' --project_id "$PROJECT"
