%% To install the mmdc command run:
%%   npm install -g mermaid.cli
%% To update this file run:
%%   mmdc -i diagram.mmd -o diagram.svg
%% Or use the docker wrapper in this repo (from the top-level directory):
%%   ./bin/update-diagrams

graph TD

f1(Producers) --> k1(Ingestion Edge)
k1 --> p1(Raw Topic)
k1 --> p99(...)

subgraph Pipeline Family: Structured
    p1 --> k2(Raw Sink)
    k2 --> c1(BigQuery)
    p1 --> d2(Decoder)
    d2 --> p2(Decoded Topic)
    d2 -.-> p2err(Error Topic)
    p2err --> d3err(Error Sink)
    d3err --> berr(BigQuery)
    p2 --> d3(Live Sink)
    d3 --> b1(BigQuery)
    p2 --> k3(Decoded Sink)
    k3 --> c2(BigQuery)
    p2 --> d5(Republisher)
    d5 --> p5(Per DocType Topics)
    d5 --> p6(Monitoring Sample Topics)
end

subgraph .
   p99 --> d99(...)
end

subgraph Colors
    d(Dataflow jobs are green)
    k(Kubernetes services are magenta)
    f(Producers are orange)
    p(PubSub topics are cyan)
    g(Google Cloud services are purple)

    %% connect them to make the key vertical
    d --- k
    k --- f
    f --- p
    p --- g
end

classDef cyan fill:#eff,stroke:#099;
classDef green fill:#efe,stroke:#090;
classDef magenta fill:#fef,stroke:#909;
classDef orange fill:#fee,stroke:#f90;
class p,p0,p1,p1aet,p2,p2err,p3,p4,p5,p6,p99 cyan
class d,d0,d2,d2aet,d5,d99 green
class k,k0,k1,k2,k3,d3,d3err magenta
class f,f1 orange
